version: 2

sources:
  - name: erp
    database: projeto-dbt-412823  
    schema: erp_northwind  
    description: Fonte de dados de vendas dos SAP northwind
    tables:
      - name: employees
        columns:
          - name: employee_id
            tests:
              - unique
              - not_null

      - name: products
        columns:
          - name: product_id
            tests:
              - unique
              - not_null

      - name: categories
        columns:
          - name: category_id
            tests:
              - unique
              - not_null

      - name: suppliers
        columns:
          - name: supplier_id
            tests:
              - unique
              - not_null
              
 